from aiogram.dispatcher.filters.state import StatesGroup, State


class select_lang(StatesGroup):
    rus = State()
    eng = State()
    uz = State()
    other = State()
    drugoe = State()
    boshqalar = State()
    sbt = State()
    tbs = State()
    nerav = State()
    buxgalter = State()
    poraxor = State()
    cor = State()
    viol = State()
    unequal = State()
    health = State()
    leakage = State()
    pora = State()
    buxgal = State()
    tengsiz = State()
    tb = State()
    sb = State()

    sbt1 = State()
    tbs1 = State()
    nerav1 = State()
    buxgalter1 = State()
    poraxor1 = State()
    cor1 = State()
    viol1 = State()
    unequal1 = State()
    health1 = State()
    leakage1 = State()
    pora1 = State()
    buxgal1 = State()
    tengsiz1 = State()
    tb1 = State()
    sb1 = State()
